fix ArgumentError usage
came across this while debugging once-ler stuff ... this way you get an
ArgumentError instead of `NoMethodError: undefined method `ArgumentError'`

Change-Id: Idb994326e1fb376f30948e000be1a23c7e5301a8
Reviewed-on: https://gerrit.instructure.com/37843
Tested-by: Jenkins <jenkins@instructure.com>
Reviewed-by: Cody Cutrer <cody@instructure.com>
Product-Review: Jon Jensen <jon@instructure.com>
QA-Review: Jon Jensen <jon@instructure.com>